// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"
	"tutorial/ent/car"
	"tutorial/ent/predicate"
	"tutorial/ent/user"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// CarUpdate is the builder for updating Car entities.
type CarUpdate struct {
	config
	hooks    []Hook
	mutation *CarMutation
}

// Where appends a list predicates to the CarUpdate builder.
func (cu *CarUpdate) Where(ps ...predicate.Car) *CarUpdate {
	cu.mutation.Where(ps...)
	return cu
}

// SetModel sets the "model" field.
func (cu *CarUpdate) SetModel(s string) *CarUpdate {
	cu.mutation.SetModel(s)
	return cu
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (cu *CarUpdate) SetNillableModel(s *string) *CarUpdate {
	if s != nil {
		cu.SetModel(*s)
	}
	return cu
}

// SetCarNumber sets the "car_number" field.
func (cu *CarUpdate) SetCarNumber(s string) *CarUpdate {
	cu.mutation.SetCarNumber(s)
	return cu
}

// SetNillableCarNumber sets the "car_number" field if the given value is not nil.
func (cu *CarUpdate) SetNillableCarNumber(s *string) *CarUpdate {
	if s != nil {
		cu.SetCarNumber(*s)
	}
	return cu
}

// SetOwnerID sets the "owner_id" field.
func (cu *CarUpdate) SetOwnerID(i int) *CarUpdate {
	cu.mutation.SetOwnerID(i)
	return cu
}

// SetNillableOwnerID sets the "owner_id" field if the given value is not nil.
func (cu *CarUpdate) SetNillableOwnerID(i *int) *CarUpdate {
	if i != nil {
		cu.SetOwnerID(*i)
	}
	return cu
}

// SetRegisteredAt sets the "registered_at" field.
func (cu *CarUpdate) SetRegisteredAt(t time.Time) *CarUpdate {
	cu.mutation.SetRegisteredAt(t)
	return cu
}

// SetNillableRegisteredAt sets the "registered_at" field if the given value is not nil.
func (cu *CarUpdate) SetNillableRegisteredAt(t *time.Time) *CarUpdate {
	if t != nil {
		cu.SetRegisteredAt(*t)
	}
	return cu
}

// SetUsersID sets the "users" edge to the User entity by ID.
func (cu *CarUpdate) SetUsersID(id int) *CarUpdate {
	cu.mutation.SetUsersID(id)
	return cu
}

// SetUsers sets the "users" edge to the User entity.
func (cu *CarUpdate) SetUsers(u *User) *CarUpdate {
	return cu.SetUsersID(u.ID)
}

// Mutation returns the CarMutation object of the builder.
func (cu *CarUpdate) Mutation() *CarMutation {
	return cu.mutation
}

// ClearUsers clears the "users" edge to the User entity.
func (cu *CarUpdate) ClearUsers() *CarUpdate {
	cu.mutation.ClearUsers()
	return cu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (cu *CarUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, cu.sqlSave, cu.mutation, cu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (cu *CarUpdate) SaveX(ctx context.Context) int {
	affected, err := cu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (cu *CarUpdate) Exec(ctx context.Context) error {
	_, err := cu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cu *CarUpdate) ExecX(ctx context.Context) {
	if err := cu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (cu *CarUpdate) check() error {
	if cu.mutation.UsersCleared() && len(cu.mutation.UsersIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Car.users"`)
	}
	return nil
}

func (cu *CarUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := cu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(car.Table, car.Columns, sqlgraph.NewFieldSpec(car.FieldID, field.TypeInt))
	if ps := cu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := cu.mutation.Model(); ok {
		_spec.SetField(car.FieldModel, field.TypeString, value)
	}
	if value, ok := cu.mutation.CarNumber(); ok {
		_spec.SetField(car.FieldCarNumber, field.TypeString, value)
	}
	if value, ok := cu.mutation.RegisteredAt(); ok {
		_spec.SetField(car.FieldRegisteredAt, field.TypeTime, value)
	}
	if cu.mutation.UsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   car.UsersTable,
			Columns: []string{car.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cu.mutation.UsersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   car.UsersTable,
			Columns: []string{car.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, cu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{car.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	cu.mutation.done = true
	return n, nil
}

// CarUpdateOne is the builder for updating a single Car entity.
type CarUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CarMutation
}

// SetModel sets the "model" field.
func (cuo *CarUpdateOne) SetModel(s string) *CarUpdateOne {
	cuo.mutation.SetModel(s)
	return cuo
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (cuo *CarUpdateOne) SetNillableModel(s *string) *CarUpdateOne {
	if s != nil {
		cuo.SetModel(*s)
	}
	return cuo
}

// SetCarNumber sets the "car_number" field.
func (cuo *CarUpdateOne) SetCarNumber(s string) *CarUpdateOne {
	cuo.mutation.SetCarNumber(s)
	return cuo
}

// SetNillableCarNumber sets the "car_number" field if the given value is not nil.
func (cuo *CarUpdateOne) SetNillableCarNumber(s *string) *CarUpdateOne {
	if s != nil {
		cuo.SetCarNumber(*s)
	}
	return cuo
}

// SetOwnerID sets the "owner_id" field.
func (cuo *CarUpdateOne) SetOwnerID(i int) *CarUpdateOne {
	cuo.mutation.SetOwnerID(i)
	return cuo
}

// SetNillableOwnerID sets the "owner_id" field if the given value is not nil.
func (cuo *CarUpdateOne) SetNillableOwnerID(i *int) *CarUpdateOne {
	if i != nil {
		cuo.SetOwnerID(*i)
	}
	return cuo
}

// SetRegisteredAt sets the "registered_at" field.
func (cuo *CarUpdateOne) SetRegisteredAt(t time.Time) *CarUpdateOne {
	cuo.mutation.SetRegisteredAt(t)
	return cuo
}

// SetNillableRegisteredAt sets the "registered_at" field if the given value is not nil.
func (cuo *CarUpdateOne) SetNillableRegisteredAt(t *time.Time) *CarUpdateOne {
	if t != nil {
		cuo.SetRegisteredAt(*t)
	}
	return cuo
}

// SetUsersID sets the "users" edge to the User entity by ID.
func (cuo *CarUpdateOne) SetUsersID(id int) *CarUpdateOne {
	cuo.mutation.SetUsersID(id)
	return cuo
}

// SetUsers sets the "users" edge to the User entity.
func (cuo *CarUpdateOne) SetUsers(u *User) *CarUpdateOne {
	return cuo.SetUsersID(u.ID)
}

// Mutation returns the CarMutation object of the builder.
func (cuo *CarUpdateOne) Mutation() *CarMutation {
	return cuo.mutation
}

// ClearUsers clears the "users" edge to the User entity.
func (cuo *CarUpdateOne) ClearUsers() *CarUpdateOne {
	cuo.mutation.ClearUsers()
	return cuo
}

// Where appends a list predicates to the CarUpdate builder.
func (cuo *CarUpdateOne) Where(ps ...predicate.Car) *CarUpdateOne {
	cuo.mutation.Where(ps...)
	return cuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (cuo *CarUpdateOne) Select(field string, fields ...string) *CarUpdateOne {
	cuo.fields = append([]string{field}, fields...)
	return cuo
}

// Save executes the query and returns the updated Car entity.
func (cuo *CarUpdateOne) Save(ctx context.Context) (*Car, error) {
	return withHooks(ctx, cuo.sqlSave, cuo.mutation, cuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (cuo *CarUpdateOne) SaveX(ctx context.Context) *Car {
	node, err := cuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (cuo *CarUpdateOne) Exec(ctx context.Context) error {
	_, err := cuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cuo *CarUpdateOne) ExecX(ctx context.Context) {
	if err := cuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (cuo *CarUpdateOne) check() error {
	if cuo.mutation.UsersCleared() && len(cuo.mutation.UsersIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Car.users"`)
	}
	return nil
}

func (cuo *CarUpdateOne) sqlSave(ctx context.Context) (_node *Car, err error) {
	if err := cuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(car.Table, car.Columns, sqlgraph.NewFieldSpec(car.FieldID, field.TypeInt))
	id, ok := cuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Car.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := cuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, car.FieldID)
		for _, f := range fields {
			if !car.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != car.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := cuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := cuo.mutation.Model(); ok {
		_spec.SetField(car.FieldModel, field.TypeString, value)
	}
	if value, ok := cuo.mutation.CarNumber(); ok {
		_spec.SetField(car.FieldCarNumber, field.TypeString, value)
	}
	if value, ok := cuo.mutation.RegisteredAt(); ok {
		_spec.SetField(car.FieldRegisteredAt, field.TypeTime, value)
	}
	if cuo.mutation.UsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   car.UsersTable,
			Columns: []string{car.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cuo.mutation.UsersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   car.UsersTable,
			Columns: []string{car.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Car{config: cuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, cuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{car.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	cuo.mutation.done = true
	return _node, nil
}
